#!/usr/bin/env php
<?php

umask(0000);

require_once __DIR__.'/../../../bootstrap.php';
require_once __DIR__.'/AppKernel.php';

$application = new Symfony\Bundle\FrameworkBundle\Console\Application(new AppKernel('test', false));
$application->run();
